### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by akohli96** [regexpressyourself/OrderUp-HookUp#1]
Sam I noticed api key is hardcoded in your app.js file(although you have technically left it out). 
I have been told its usually better to export as env variable and call it or add a .gitignore file with key in it.

**Comment by regexpressyourself** [comment]
Thanks Ayush!

I knew there had to be a better way of doing that. I ended up going with the dotenv module (https://github.com/motdotla/dotenv) to create an environment variable, and gitignore-ing the .env file itself. Works great!

Fixed here: https://github.com/regexpressyourself/OrderUp-HookUp/commit/3b3d9c7491ab1d24d9c417f1e6d200f65c370c6c

**Comment by akohli96** [comment]
Thats great to know! In python, I usually call os.env to get from .bashrc.

Once you know one you sort of know all ... I guess...

**Comment by regexpressyourself** [comment]
Huh. So is .bashrc similar to/the same as a list of environment variables? 

With node, it looks like you can declare them when you start the server:

`MYTOKEN=tokenid node app.js`

The problem here being that you need to do this everytime you start the server, which doesn't quite jive with my deployment environment. The module just makes it a little easier.

Learning everyday!

**Comment by akohli96** [comment]
Yes, so you export Variables in bash or you store variables in bash rc and in python atleast you can 
call os.getenv('KEY_THAT_MIGHT_EXIST', default_value) 

You could create a config file with a dictionary that has keys and values and use a similar mechanism.

Thats how Kali gets cat photos by importing a dictionary from config.py which contains keys ([https://github.com/akohli96/Kali/blob/master/Py-Bot/popularcat.py](url)

Whatever you are comfortable with tbh

**Comment by akohli96** [comment]
@regexpressyourself Jacob introduced me to Travis CI which helps you build and test your code. I have been playing with it and seems to take away the manual labor. Its highly customisable and can handle environment variables for you!!  [https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings](url)

Learning something new everyday
